### ISSUE TITLE
Broken codelist links in schema browser

### ISSUE THREAD

**Issue by rhiaro** [openownership/data-standard#225] opened 2019-07-10 10:28 UTC
This is not new: issue exists in 0.1 docs.

Links to codelists in schema description fields are done using local anchors, in markdown syntax: https://github.com/openownership/data-standard/blob/master/schema/person-statement.json#L30

This works correctly in the *schema reference* (for now - will need an update to RST link syntax if we remove all markdown parsing).

But when docson renders these in the *schema browser*, it scopes them to its own root which is wrong, but also the anchors don't exist on the schema browser page anyway as the link needs to be to codelists. Eg. go to http://standard.openownership.org/en/v0-1/schema/schema-browser.html#person-statement and look at `personType` ("Use the personType codelist."). The link should be to http://standard.openownership.org/en/v0-1/schema/reference.html#persontype

Proposed solution: replace markdown anchor links in schema description with RST references, ie. the above should go from:

    Use the [personType codelist](#persontype)

to

    Use the :ref:`personType codelist <persontype>`

Note: not tested. May need to add label to the codelists in `reference.rst`, ie.

```
.. _persontype:

PersonType
++++++++++
```

([Sphinx ref docs](http://www.sphinx-doc.org/en/stable/usage/restructuredtext/roles.html#cross-referencing-arbitrary-locations))

**Comment by odscjames** [comment] 2019-07-17 09:53
Dupe of #136

**Closed** 2019-07-17 18:23 UTC
Labels: bug, documentation content
